version: "3"
services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - /home/gitpod/mc:/data
    environment:
      - MEMORY=2048
      - USER_ID=33333
      - GROUP_ID=33333
    tty: true
    stdin_open: true